server:
    port: 8082
    servlet:
        context-path: /companyservice
spring:
    application:
        name: company-service
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/companyserviceDB?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default:
                    schema: companyserviceDB
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                show_sql: true
                temp:
                    use_jdbc_metadata_defaults: false

