
#server.port=8081
#spring.datasource.url = jdbc:mysql://localhost:3306/employeeservice?createDatabaseIfNotExist=true
#spring.application.name=employee-service
#spring.datasource.username = root
#spring.datasource.password = root
#server.servlet.context-path=/employeeservice
##For 1st time data creation set to -> create
##spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto =create
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.default.schema=employeeservice
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true





server:
    port: 8081
    servlet:
        context-path: /employeeservice
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/employeeserviceDB?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default:
                    schema: employeeserviceDB
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                show_sql: true
                temp:
                    use_jdbc_metadata_defaults: false
